EVENT_FLAG_MAPPING = {
    [0] = { value = 0, code = "defeat_brock" },
    [1] = { value = 0, code = "defeat_misty" },
    [2] = { value = 0, code = "defeat_lt_surge" },
    [3] = { value = 0, code = "defeat_erika" },
    [4] = { value = 0, code = "defeat_koga" },
    [5] = { value = 0, code = "defeat_sabrina" },
    [6] = { value = 0, code = "defeat_blaine" },
    [7] = { value = 0, code = "defeat_giovanni" },
    [8] = { value = 0, code = "deliver_oaks_parcel" },
    [9] = { value = 0, code = "defeat_route_22_rival" },
    [10] = { value = 0, code = "save_bill" },
    [11] = { value = 0, code = "rescue_mr_fuji" },
    [12] = { value = 0, code = "liberate_silph_co" },
    [13] = { value = 0, code = "defeat_champion" },
    [14] = { value = 0, code = "rescue_lostelle" },
    [15] = { value = 0, code = "deliver_meteorite" },
    [16] = { value = 0, code = "learn_goldeen_need_log" },
    [17] = { value = 0, code = "help_lorelei" },
    [18] = { value = 0, code = "rescue_selphy" },
    [19] = { value = 0, code = "learn_yes_nah_chansey" },
    [20] = { value = 0, code = "free_captured_pokemon" },
    [21] = { value = 0, code = "unlock_ruins" },
    [22] = { value = 0, code = "restore_pokemon_network_machine" },
    [23] = { value = 0, code = "defeat_champion_rematch" },
    [24] = { value = 0, code = "lemonade" },
    [25] = { value = 0, code = "running_shoes" }
}

FLY_UNLOCK_FLAG_MAPPING = {
    [0] = { value = 0, code = "pallet_fly_unlock" },
    [1] = { value = 0, code = "viridian_fly_unlock" },
    [2] = { value = 0, code = "pewter_fly_unlock" },
    [3] = { value = 0, code = "route_4_fly_unlock" },
    [4] = { value = 0, code = "cerulean_fly_unlock" },
    [5] = { value = 0, code = "vermilion_fly_unlock" },
    [6] = { value = 0, code = "route_10_fly_unlock" },
    [7] = { value = 0, code = "lavender_fly_unlock" },
    [8] = { value = 0, code = "celadon_fly_unlock" },
    [9] = { value = 0, code = "fuchsia_fly_unlock" },
    [10] = { value = 0, code = "saffron_fly_unlock" },
    [11] = { value = 0, code = "cinnabar_fly_unlock" },
    [12] = { value = 0, code = "indigo_fly_unlock" },
    [13] = { value = 0, code = "one_island_fly_unlock" },
    [14] = { value = 0, code = "two_island_fly_unlock" },
    [15] = { value = 0, code = "three_island_fly_unlock" },
    [16] = { value = 0, code = "four_island_fly_unlock" },
    [17] = { value = 0, code = "five_island_fly_unlock" },
    [18] = { value = 0, code = "six_island_fly_unlock" },
    [19] = { value = 0, code = "seven_island_fly_unlock" }
}
