EVENT_FLAG_MAPPING = {
    [0] = { value = 0, code = "defeat_brock" },
    [1] = { value = 0, code = "defeat_misty" },
    [2] = { value = 0, code = "defeat_lt_surge" },
    [3] = { value = 0, code = "defeat_erika" },
    [4] = { value = 0, code = "defeat_koga" },
    [5] = { value = 0, code = "defeat_sabrina" },
    [6] = { value = 0, code = "defeat_blaine" },
    [7] = { value = 0, code = "defeat_giovanni" },
    [8] = { value = 0, code = "deliver_oaks_parcel" },
    [9] = { value = 0, code = "defeat_route_22_rival" },
    [10] = { value = 0, code = "save_bill" },
    [11] = { value = 0, code = "rescue_mr_fuji" },
    [12] = { value = 0, code = "liberate_silph_co" },
    [13] = { value = 0, code = "defeat_champion" },
    [14] = { value = 0, code = "rescue_lostelle" },
    [15] = { value = 0, code = "deliver_meteorite" },
    [16] = { value = 0, code = "learn_goldeen_need_log" },
    [17] = { value = 0, code = "help_lorelei" },
    [18] = { value = 0, code = "rescue_selphy" },
    [19] = { value = 0, code = "learn_yes_nah_chansey" },
    [20] = { value = 0, code = "free_captured_pokemon" },
    [21] = { value = 0, code = "unlock_ruins" },
    [22] = { value = 0, code = "restore_pokemon_network_machine" },
    [23] = { value = 0, code = "defeat_champion_rematch" },
    [24] = { value = 0, code = "lemonade" },
    [25] = { value = 0, code = "running_shoes" }
}

FLY_UNLOCK_FLAG_MAPPING = {
    [0] = { value = 0, code = "fly_pallet" },
    [1] = { value = 0, code = "fly_viridian" },
    [2] = { value = 0, code = "fly_pewter" },
    [3] = { value = 0, code = "fly_route_4" },
    [4] = { value = 0, code = "fly_cerulean" },
    [5] = { value = 0, code = "fly_vermilion" },
    [6] = { value = 0, code = "fly_route_10" },
    [7] = { value = 0, code = "fly_lavender" },
    [8] = { value = 0, code = "fly_celadon" },
    [9] = { value = 0, code = "fly_fuchsia" },
    [10] = { value = 0, code = "fly_saffron" },
    [11] = { value = 0, code = "fly_cinnabar" },
    [12] = { value = 0 , code = "fly_indigo" },
    [13] = { value = 0, code = "fly_one_island" },
    [14] = { value = 0, code = "fly_two_island" },
    [15] = { value = 0, code = "fly_three_island" },
    [16] = { value = 0, code = "fly_four_island" },
    [17] = { value = 0, code = "fly_five_island" },
    [18] = { value = 0, code = "fly_six_island" },
    [19] = { value = 0, code = "fly_seven_island" }
}
