ScriptHost:LoadScript("scripts/custom_items/class.lua")
ScriptHost:LoadScript("scripts/custom_items/custom_item.lua")
ScriptHost:LoadScript("scripts/custom_items/badges_gyms_requirement.lua")
ScriptHost:LoadScript("scripts/custom_items/cerulean_cave_requirement.lua")
ScriptHost:LoadScript("scripts/custom_items/pokedex.lua")
ScriptHost:LoadScript("scripts/custom_items/pokedex_requirement.lua")

E4_REQ = BadgesGymsRequirement("Elite Four Requirement", "elite_four_requirement", 8, 8)
E4_REMATCH_REQ = BadgesGymsRequirement("Elite Four Rematch Requirement", "elite_four_rematch_requirement", 8, 8)
ROUTE_22_REQ = BadgesGymsRequirement("Route 22 Gate Requirement", "route_22_gate_requirement", 7, 8)
ROUTE_23_REQ = BadgesGymsRequirement("Route 23 Guard Requirement", "route_23_guard_requirement", 7, 8)
VIRIDIAN_GYM_REQ = BadgesGymsRequirement("Viridian Gym Requirement", "viridian_gym_requirement", 7, 7)
CERULEAN_CAVE_REQ = CeruleanCaveRequirement()
OAKS_AIDE_ROUTE_2_REQ = PokedexRequirement("Route 2 Oak's Aide Requirement", "route_2_oaks_aide_requirement", 5)
OAKS_AIDE_ROUTE_10_REQ = PokedexRequirement("Route 10 Oak's Aide Requirement", "route_10_oaks_aide_requirement", 10)
OAKS_AIDE_ROUTE_11_REQ = PokedexRequirement("Route 11 Oak's Aide Requirement", "route_11_oaks_aide_requirement", 15)
OAKS_AIDE_ROUTE_16_REQ = PokedexRequirement("Route 16 Oak's Aide Requirement", "route_16_oaks_aide_requirement", 20)
OAKS_AIDE_ROUTE_15_REQ = PokedexRequirement("Route 15 Oak's Aide Requirement", "route_15_oaks_aide_requirement", 25)
POKEDEX = Pokedex()