ScriptHost:LoadScript("scripts/custom_items/class.lua")
ScriptHost:LoadScript("scripts/custom_items/custom_item.lua")
ScriptHost:LoadScript("scripts/custom_items/badges_gyms_requirement.lua")
ScriptHost:LoadScript("scripts/custom_items/cerulean_cave_requirement.lua")
ScriptHost:LoadScript("scripts/custom_items/dungeon_entrance.lua")
ScriptHost:LoadScript("scripts/custom_items/fly_destination.lua")
ScriptHost:LoadScript("scripts/custom_items/pokedex.lua")
ScriptHost:LoadScript("scripts/custom_items/pokedex_requirement.lua")

E4_REQ = BadgesGymsRequirement("Elite Four Requirement", "elite_four_requirement", 8, 8)
E4_REMATCH_REQ = BadgesGymsRequirement("Elite Four Rematch Requirement", "elite_four_rematch_requirement", 8, 8)
ROUTE_22_REQ = BadgesGymsRequirement("Route 22 Gate Requirement", "route_22_gate_requirement", 7, 8)
ROUTE_23_REQ = BadgesGymsRequirement("Route 23 Guard Requirement", "route_23_guard_requirement", 7, 8)
VIRIDIAN_GYM_REQ = BadgesGymsRequirement("Viridian Gym Requirement", "viridian_gym_requirement", 7, 7)
CERULEAN_CAVE_REQ = CeruleanCaveRequirement()
VIRIDIAN_FOREST_SOUTH = DungeonEntrance("Viridian Forest South", "viridian_forest_south", 1)
VIRIDIAN_FOREST_NORTH = DungeonEntrance("Viridian Forest North", "viridian_forest_north", 2)
MT_MOON_WEST = DungeonEntrance("Mt. Moon West", "mt_moon_west", 3)
MT_MOON_EAST = DungeonEntrance("Mt. Moon East", "mt_moon_east", 4)
SS_ANNE = DungeonEntrance("S.S. Anne", "ss_anne", 5)
DIGLETTS_CAVE_NORTH = DungeonEntrance("Diglett's Cave North", "digletts_cave_north", 6)
DIGLETTS_CAVE_SOUTH = DungeonEntrance("Diglett's Cave South", "digletts_cave_south", 7)
ROCK_TUNNEL_NORTH = DungeonEntrance("Rock Tunnel North", "rock_tunnel_north", 8)
ROCK_TUNNEL_SOUTH = DungeonEntrance("Rock Tunnel South", "rock_tunnel_south", 9)
POWER_PLANT_FRONT = DungeonEntrance("Power Plant Front", "power_plant_front", 10)
POWER_PLANT_BACK = DungeonEntrance("Power Plant Back", "power_plant_back", 11)
POKEMON_TOWER = DungeonEntrance("Pokémon Tower", "pokemon_tower", 12)
ROCKET_HIDEOUT = DungeonEntrance("Rocket Hideout", "rocket_hideout", 13)
SAFARI_ZONE = DungeonEntrance("Safari Zone", "safari_zone", 14)
SILPH_CO = DungeonEntrance("Silph Co.", "silph_co", 15)
SEAFOAM_ISLANDS_SOUTH = DungeonEntrance("Seafoam Islands South", "seafoam_islands_south", 16)
SEAFOAM_ISLANDS_NORTH = DungeonEntrance("Seafoam Islands North", "seafoam_islands_north", 17)
POKEMON_MANSION = DungeonEntrance("Pokémon Mansion", "pokemon_mansion", 18)
VICTORY_ROAD_WEST = DungeonEntrance("Victory Road West", "victory_road_west", 19)
VICTORY_ROAD_EAST = DungeonEntrance("Victory Road East", "victory_road_east", 20)
MT_EMBER = DungeonEntrance("Mt. Ember", "mt_ember", 21)
BERRY_FOREST = DungeonEntrance("Berry Forest", "berry_forest", 22)
ICEFALL_CAVE = DungeonEntrance("Icefall Cave", "icefall_cave", 23)
ROCKET_WAREHOUSE = DungeonEntrance("Rocket Warehouse", "rocket_warehouse", 24)
LOST_CAVE = DungeonEntrance("Lost Cave", "lost_cave", 25)
DOTTED_HOLE = DungeonEntrance("Dotted Hole", "dotted_hole", 26)
PATTERN_BUSH_WEST = DungeonEntrance("Pattern Bush West", "pattern_bush_west", 27)
PATTERN_BUSH_EAST = DungeonEntrance("Pattern Bush East", "pattern_bush_east", 28)
ALTERING_CAVE = DungeonEntrance("Altering Cave", "altering_cave", 29)
MONEAN_CHAMBER = DungeonEntrance("Monean Chamber", "monean_chamber", 30)
LIPTOO_CHAMBER = DungeonEntrance("Liptoo Chamber", "liptoo_chamber", 31)
WEEPTH_CHAMBER = DungeonEntrance("Weepth Chamber", "weepth_chamber", 32)
DILFORD_CHAMBER = DungeonEntrance("Dilford Chamber", "dilford_chamber", 33)
SCUFIB_CHAMBER = DungeonEntrance("Scufib Chamber", "scufib_chamber", 34)
RIXY_CHAMBER = DungeonEntrance("Rixy Chamber", "rixy_chamber", 35)
VIAPOIS_CHAMBER = DungeonEntrance("Viapois Chamber", "viapois_chamber", 36)
CERULEAN_CAVE = DungeonEntrance("Cerulean Cave", "cerulean_cave", 37)
NAVEL_ROCK = DungeonEntrance("Navel Rock", "navel_rock", 38)
PALLET_FLY_DESTINATION = FlyDestination("Pallet Fly Destination", "pallet", 1)
VIRIDIAN_FLY_DESTINATION = FlyDestination("Viridian Fly Destination", "viridian", 2)
PEWTER_FLY_DESTINATION = FlyDestination("Pewter Fly Destination", "pewter", 10)
ROUTE_4_FLY_DESTINATION = FlyDestination("Route 4 Fly Destination", "route_4", 12)
CERULEAN_FLY_DESTINATION = FlyDestination("Cerulean Fly Destination", "cerulean", 14)
VERMILION_FLY_DESTINATION = FlyDestination("Vermilion Fly Destination", "vermilion", 23)
ROUTE_10_FLY_DESTINATION = FlyDestination("Route 10 Fly Destination", "route_10", 28)
LAVENDER_FLY_DESTINATION = FlyDestination("Lavender Fly Destination", "lavender", 32)
CELADON_FLY_DESTINATION = FlyDestination("Celadon Fly Destination", "celadon", 37)
FUCHSIA_FLY_DESTINATION = FlyDestination("Fuchsia Fly Destination", "fuchsia", 48)
SAFFRON_FLY_DESTINATION = FlyDestination("Saffron Fly Destination", "saffron", 50)
CINNABAR_FLY_DESTINATION = FlyDestination("Cinnabar Fly Destination", "cinnabar", 53)
INDIGO_FLY_DESTINATION = FlyDestination("Indigo Fly Destination", "indigo", 57)
ONE_ISLAND_FLY_DESTINATION = FlyDestination("One Island Fly Destination", "one_island", 58)
TWO_ISLAND_FLY_DESTINATION = FlyDestination("Two Island Fly Destination", "two_island", 61)
THREE_ISLAND_FLY_DESTINATION = FlyDestination("Three Island Fly Destination", "three_island", 65)
FOUR_ISLAND_FLY_DESTINATION = FlyDestination("Four Island Fly Destination", "four_island", 68)
FIVE_ISLAND_FLY_DESTINATION = FlyDestination("Five Island Fly Destination", "five_island", 70)
SIX_ISLAND_FLY_DESTINATION = FlyDestination("Six Island Fly Destination", "six_island", 74)
SEVEN_ISLAND_FLY_DESTINATION = FlyDestination("Seven Island Fly Destination", "seven_island", 80)
OAKS_AIDE_ROUTE_2_REQ = PokedexRequirement("Route 2 Oak's Aide Requirement", "route_2_oaks_aide_requirement", 5)
OAKS_AIDE_ROUTE_10_REQ = PokedexRequirement("Route 10 Oak's Aide Requirement", "route_10_oaks_aide_requirement", 10)
OAKS_AIDE_ROUTE_11_REQ = PokedexRequirement("Route 11 Oak's Aide Requirement", "route_11_oaks_aide_requirement", 15)
OAKS_AIDE_ROUTE_16_REQ = PokedexRequirement("Route 16 Oak's Aide Requirement", "route_16_oaks_aide_requirement", 20)
OAKS_AIDE_ROUTE_15_REQ = PokedexRequirement("Route 15 Oak's Aide Requirement", "route_15_oaks_aide_requirement", 25)
POKEDEX = Pokedex()