Tracker:AddItems("items/dungeon_entrances.json")
Tracker:AddItems("items/events.json")
Tracker:AddItems("items/events_hosted.json")
Tracker:AddItems("items/items.json")
Tracker:AddItems("items/items_hosted.json")
Tracker:AddItems("items/pokemon.json")
Tracker:AddItems("items/settings.json")
Tracker:AddItems("items/trainer_visibility.json")